apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-agent
  template:
    metadata:
      labels:
        app: weather-agent
    spec:
      containers:
      - name: weather-agent-container
        image: abid8/weather-agent:v3 # <-- CHANGE THIS
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: weather-agent-service
spec:
  selector:
    app: weather-agent
  ports:
  - port: 80
    targetPort: 8001